import Phaser from 'phaser';
import { Card } from '../entities/Card';
import { Deck } from '../entities/Deck';
import { EventBus } from '../manager/EventBus';
import { CARD_LEVELS, CardLevelData } from '../data/LevelData';

/**
 * ============================================================
 * CardTable.ts
 * ============================================================
 * WHAT THIS FILE DOES:
 * The main hub scene. Flow:
 *   1. Shows the Deck (pile + name label).
 *   2. Click deck -> shuffle animation -> deck disappears, 5 Cards
 *      fan out from CARD_LEVELS (see data/LevelData.ts).
 *   3. Hovering a card swaps the table background to that card's
 *      `backgroundKey` scenery. Un-hovering restores the default.
 *   4. Clicking PLAY on a card zooms in, then this scene starts the
 *      level's `targetSceneKey` (also from LevelData.ts).
 *
 * WHAT YOU CAN CUSTOMIZE:
 *   - Card layout spacing/position: see `layoutCards()`.
 *   - Default (no-hover) table background: change DEFAULT_BG_KEY
 *     or the color inside `generatePlaceholderTextures()`.
 *   - Deck starting position / player name label: see `create()`,
 *     the `new Deck({...})` call.
 *   - The actual list of cards/levels: DO NOT edit this file — edit
 *     src/game/data/LevelData.ts instead.
 * ============================================================
 */
export class CardTable extends Phaser.Scene {
  private cards: Card[] = [];
  private background!: Phaser.GameObjects.Image;
  private deck!: Deck;

  private readonly CARD_WIDTH = 120;
  private readonly CARD_HEIGHT = 168;
  private readonly DEFAULT_BG_KEY = 'bg-placeholder-default';

  constructor() {
    super('CardTable');
  }

  preload(): void {
    // --- Real assets go here once you have them ---
    // this.load.image('table-bg-default', 'assets/images/backgrounds/table.png');
    // this.load.image('table-bg-forest', 'assets/images/backgrounds/forest.png');
    // this.load.image('card-back', 'assets/images/cards/card-back.png');
    // (Also see Preload.ts for a centralized place to put these instead.)
  }

  create(): void {
    this.generatePlaceholderTextures();

    const { width, height } = this.scale;

    // Default table background (shown when nothing is hovered).
    this.background = this.add.image(width / 2, height / 2, this.DEFAULT_BG_KEY);
    this.background.setDisplaySize(width, height);

    // --- Deck (shown first) ---
    // Change 'Player Name' below to a real name, or wire it up to
    // props/EventBus data coming from your React login/profile system.
    this.deck = new Deck({
      scene: this,
      x: width / 2,
      y: height / 2,
      label: 'Player Name',
      backKey: 'card-back-placeholder',
      onShuffleComplete: () => this.layoutCards(),
    });

    EventBus.emit('current-scene-ready', this);
  }

  /** Called by Deck once the shuffle animation finishes. Fans out the 5 cards. */
  private layoutCards(): void {
    const { width, height } = this.scale;
    const spacing = this.CARD_WIDTH + 24; // <-- gap between cards, tweak here
    const totalWidth = spacing * (CARD_LEVELS.length - 1);
    const startX = width / 2 - totalWidth / 2;
    const y = height / 2;

    CARD_LEVELS.forEach((levelData, i) => {
      const card = new Card({
        scene: this,
        x: startX + i * spacing,
        y,
        width: this.CARD_WIDTH,
        height: this.CARD_HEIGHT,
        data: levelData,
        onHover: (data) => this.swapBackground(data),
        onHoverEnd: () => this.restoreBackground(),
        onPlay: (data) => this.launchLevel(data),
      });

      // Cards fly in from slightly above their resting position for a
      // nice "dealt onto the table" feel. Adjust the -40 / duration to taste.
      card.y -= 40;
      card.setAlpha(0);
      this.tweens.add({
        targets: card,
        y: y,
        alpha: 1,
        duration: 300,
        delay: i * 80, // <-- stagger between each card dealing in
        ease: 'Sine.easeOut',
      });

      this.cards.push(card);
    });
  }

  /** Swaps the table background to match the hovered card's scenery. */
  private swapBackground(data: CardLevelData): void {
    this.tweens.add({
      targets: this.background,
      alpha: 0,
      duration: 150,
      onComplete: () => {
        this.background.setTexture(data.backgroundKey);
        this.background.setDisplaySize(this.scale.width, this.scale.height);
        this.tweens.add({ targets: this.background, alpha: 1, duration: 150 });
      },
    });
  }

  private restoreBackground(): void {
    this.tweens.add({
      targets: this.background,
      alpha: 0,
      duration: 150,
      onComplete: () => {
        this.background.setTexture(this.DEFAULT_BG_KEY);
        this.background.setDisplaySize(this.scale.width, this.scale.height);
        this.tweens.add({ targets: this.background, alpha: 1, duration: 150 });
      },
    });
  }

  /** Called after a card's zoom-in animation finishes. Starts the target scene. */
  private launchLevel(data: CardLevelData): void {
    if (!data.targetSceneKey) return; // safety guard for locked/unassigned cards
    this.scene.start(data.targetSceneKey);
  }

  /**
   * Draws simple placeholder textures at runtime (card backs/fronts,
   * default background, and one tinted background per card) so the
   * whole scene works with zero external art. Delete/trim this once
   * you load real images in Preload.ts and point LevelData.ts at them.
   */
  private generatePlaceholderTextures(): void {
    const w = this.CARD_WIDTH;
    const h = this.CARD_HEIGHT;

    // Card back (shared by all cards + the deck pile)
    const back = this.make.graphics({ x: 0, y: 0 }, false);
    back.fillStyle(0x2b3a67, 1);
    back.fillRoundedRect(0, 0, w, h, 10);
    back.lineStyle(4, 0xf4a259, 1);
    back.strokeRoundedRect(2, 2, w - 4, h - 4, 8);
    back.generateTexture('card-back-placeholder', w, h);
    back.destroy();

    // One front texture + one background texture per card, using the
    // card's own placeholderColor from LevelData.ts.
    CARD_LEVELS.forEach((levelData, i) => {
      const front = this.make.graphics({ x: 0, y: 0 }, false);
      front.fillStyle(0xffffff, 1);
      front.fillRoundedRect(0, 0, w, h, 10);
      front.fillStyle(levelData.placeholderColor, 1);
      front.fillRoundedRect(6, 6, w - 12, h - 12, 8);
      front.generateTexture(levelData.frontKey, w, h);
      front.destroy();

      const bg = this.make.graphics({ x: 0, y: 0 }, false);
      bg.fillStyle(levelData.placeholderColor, 0.35);
      bg.fillRect(0, 0, this.scale.width, this.scale.height);
      bg.generateTexture(levelData.backgroundKey, this.scale.width, this.scale.height);
      bg.destroy();
    });

    // Default (no hover) background
    const defaultBg = this.make.graphics({ x: 0, y: 0 }, false);
    defaultBg.fillStyle(0x1b5e3a, 1); // <-- default table color (a felt-green), tweak here
    defaultBg.fillRect(0, 0, this.scale.width, this.scale.height);
    defaultBg.generateTexture(this.DEFAULT_BG_KEY, this.scale.width, this.scale.height);
    defaultBg.destroy();
  }
}
